spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/db_security
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Perico.1029}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

custom:
  secret-key: ${SECRET_KEY:3777217A25432646294A404E635266556A586E3272357538782F413F4428472D}